In [1]:
%load_ext autoreload
%autoreload 2
%cd /home/abraham/uni/ikt453/project/v1

/home/abraham/uni/ikt453/project/v1

In [2]:
from collections import defaultdict
from copy import deepcopy
from uuid import uuid4

from src.utils import disk
from src.utils import debug

In [3]:
pr = 'data/samples/prospects.json'
dr = 'data/samples_nbaapi/drafts.json'
dh = 'data/samples_nbaapi/drafthistory.json'

pr = disk.read_json(pr)
dr = disk.read_json(dr)
dh = disk.read_json(dh)

In [16]:
from src.processing.ids import id_mapper, IDMapper

In [17]:
def construct_college_team_dimension(pr: dict, id_mapper: IDMapper) -> tuple[list, list, list, dict]:
    # TODO: Ignored fields draft/venue, draft/start_date, draft/end_date, draft/league

    pr = deepcopy(pr)
    
    list_of_prospects: list[dict] = pr['prospects']

    draft_year = pr['draft']['year']

    college_teams = []
    prospects = []

    # --------------------------
    # Helper function to construct entries for conference, division, and team
    # --------------------------
    def to_entry(namespace: str, prefix: str, obj: dict, mappings: str, provider: str, provider_id: str) -> dict:
        entry = {}
        alias = obj.get('alias')
        kwargs = {k: obj.get(k) for k in mappings}

        if alias:
            obj_id = id_mapper(namespace, alias, provider, provider_id, str(uuid4()))
            entry = {
                f'{prefix}_id': obj_id,
                f'{prefix}_alias': alias,
                **{f'{prefix}_{k}': v for k, v in kwargs.items()}
            }

        return entry

    for prospect in list_of_prospects:
        # --------------------------
        # Construct entries for conference, division, and team
        # --------------------------
        conference: dict = prospect.pop('conference', {})
        division: dict = prospect.pop('division', {})
        team: dict = prospect.pop('team', {})

        conference_entry = to_entry(
            namespace='conference',
            prefix='conference',
            obj=conference,
            mappings=('name', ),
            provider='sportsradar',
            provider_id=conference.get('id'),
        )
        
        division_entry = to_entry(
            namespace='division',
            prefix='division',
            obj=division,
            mappings=('name', ),
            provider='sportsradar',
            provider_id=division.get('id'),
        )

        team_entry = to_entry(
            namespace='team',
            prefix='team',
            obj=team,
            mappings=('name', 'market'),
            provider='sportsradar',
            provider_id=team.get('id'),
        )

        college_teams.append({
            **team_entry, 
            **division_entry, 
            **conference_entry
        })

        # --------------------------
        # Construct prospect entry
        # --------------------------
        prospect.pop('source_id', None)

        college_team_entry = college_teams[-1]

        birthplace = prospect.pop('birth_place', '').split(',')
        birthplace = zip(('city', 'state', 'country'), birthplace)
        birthplace = {f'birth_{k}':v.strip() or None for k, v in birthplace}
        
        p_id = id_mapper('prospect', prospect['name'], 'sportsradar', prospect.pop('id'), str(uuid4()))
        
        prospects.append({
            'prospect_id': p_id,
            'draft_year': draft_year,
            **prospect,
            **birthplace,
            'team_id': college_team_entry.get('team_id'),
        })

    return college_teams, prospects

In [18]:
college_teams, prospects = construct_college_team_dimension(pr, id_mapper)

In [19]:
len(college_teams), len(pr['prospects'])

(121, 121)

In [20]:
# debug.prettyprint(prospects, ensure_ascii=False)
debug.prettyprint(id_mapper.ids, ensure_ascii=False)

{
    "conference": {
        "BIG10": {
            "sportsradar": "a30fe8ff-82d2-4521-bc8d-e08e6a9dbb52",
            "custom": "9fee523c-714a-4375-9e36-b64ea2906dad"
        },
        "SEC": {
            "sportsradar": "9ed9d01e-977c-4ba7-ac7d-64035039461c",
            "custom": "ba010e49-0976-4d78-9bc6-e430b367cbc3"
        },
        "BIG12": {
            "sportsradar": "2853cf4d-6d62-4ec6-8e2c-d69f7a01a557",
            "custom": "7aef958f-4425-406b-9bba-9c88cbc77b06"
        },
        "ACC": {
            "sportsradar": "88368ebb-01fb-44d5-a6c6-3e7d46bb3ab7",
            "custom": "4737351c-a153-4c19-90e3-751073dc4a44"
        },
        "MWC": {
            "sportsradar": "93a776e4-d390-48e1-95bb-74945457366a",
            "custom": "9fff4609-b60f-47ce-b881-990e44e8575a"
        },
        "BIGEAST": {
            "sportsradar": "d07bc93e-c84c-44a9-a99d-c213bd0014d6",
            "custom": "d447fcf3-b42b-47f9-a09e-f2d14b6ee05e"
        },
        "IVY": {
            "sportsradar": "c2d16439-b791-4f9b-84d9-80cf457a0676",
            "custom": "7bdb2f0d-1f6f-414a-9980-e914e51f8349"
        },
        "SUMMIT": {
            "sportsradar": "49665f99-1a5f-434f-b841-ddde229f0eb9",
            "custom": "73cd6010-f634-4a68-9cfd-c6dc188d8112"
        },
        "AAC": {
            "sportsradar": "3b6a48d8-1f9c-484f-8ed0-ef0a540a0efe",
            "custom": "4e5f37fc-52ec-4f89-b315-a43270c28807"
        },
        "SUNBELT": {
            "sportsradar": "302c99fe-6b0a-40ec-8ee7-f15a0355b7b5",
            "custom": "be055063-ca50-4d2a-a4bc-fc5b8a37da28"
        },
        "A10": {
            "sportsradar": "db136c00-f45b-4af6-bc7d-ffff216f2e5d",
            "custom": "f8cd9fd4-7dc0-480e-a917-f151ffa0e7f1"
        },
        "WCC": {
            "sportsradar": "c664ceee-1dc0-4743-a6d8-11fbdfb87f61",
            "custom": "5110e046-b109-4cbb-b8db-a14704ad0ad4"
        },
        "CUSA": {
            "sportsradar": "6902bb03-02f7-4da4-8261-de5fd2cbd011",
            "custom": "1ce89887-72b9-4bfe-8088-8932510c8557"
        }
    },
    "division": {
        "D1": {
            "sportsradar": "c5a8d640-5093-4044-851d-2c562e929994",
            "custom": "9f62df09-a6a8-411f-8437-fd76d7884719"
        }
    },
    "team": {
        "NEB": {
            "sportsradar": "f8b1bf00-5b73-4ac4-98c0-ec554027ae32",
            "custom": "a57cf657-164c-4683-9590-5046c4deb46c"
        },
        "OKLA": {
            "sportsradar": "b2fda957-e15c-4fb2-8a13-6e58496f561e",
            "custom": "054cf782-8710-4ac7-8b8a-1b97b14b7851"
        },
        "MIZZ": {
            "sportsradar": "77ca152a-cb2f-48a5-97b2-492351250d94",
            "custom": "d5c6ff3d-9b5d-41cf-b559-4a8bb7b54fa0"
        },
        "ALA": {
            "sportsradar": "c2104cdc-c83d-40d2-a3cd-df986e29f5d3",
            "custom": "1a55c535-afc5-4fdb-bbba-ae17ea9735da"
        },
        "UK": {
            "sportsradar": "2267a1f4-68f6-418b-aaf6-2aa0c4b291f1",
            "custom": "619eb2fe-b550-4f2f-9957-ec3dc55eec28"
        },
        "TENN": {
            "sportsradar": "b827dbdf-230f-4916-9703-3bb9004e26eb",
            "custom": "be15345b-92c9-4a22-9696-96fedf6bfeda"
        },
        "FLA": {
            "sportsradar": "912f8837-1d81-4ef9-a576-a21f271d4c64",
            "custom": "41e34961-9d8f-483f-808c-3e6640656b8a"
        },
        "UGA": {
            "sportsradar": "4f4b0771-994c-4126-822d-7525aaa00f65",
            "custom": "87a73402-dae7-4dd1-9dcb-8c23d12a4c59"
        },
        "ARIZ": {
            "sportsradar": "9b166a3f-e64b-4825-bb6b-92c6f0418263",
            "custom": "8b010e37-7bd8-44a1-add7-6d6d2b220e80"
        },
        "SCAR": {
            "sportsradar": "1c7ec608-3b36-4cee-adac-9265e3792597",
            "custom": "e09a5b79-578a-47f1-94db-3ed5c8e2fd49"
        },
        "RUTG": {
            "sportsradar": "b03bb029-4499-4a2c-9074-5071ed360b21",
            "custom": "66f0b3be-7b81-4a9d-997c-9926e436a509"
        },
        "DUKE": {
            "sportsradar": "faeb1160-5d15-4f26-99fc-c441cf21fc7f",
            "custom": "a8c0c019-9c6b-49e8-8bfa-ede07d14a907"
        },
        "ILL": {
            "sportsradar": "150148c2-ca8f-414f-8f41-d94a55d4a122",
            "custom": "b6b38aef-c2a1-4623-8fa8-7f3a69afeeaa"
        },
        "CSU": {
            "sportsradar": "1a470730-f328-4fb1-8bbf-36a069e4d6b2",
            "custom": "d7ffbd26-09f6-45d1-9fad-e5f6893e3ca4"
        },
        "GTWN": {
            "sportsradar": "8736b67f-5924-400b-bf94-3bd804c36600",
            "custom": "709b408a-891c-431f-8b14-2ecc15b52805"
        },
        "MD": {
            "sportsradar": "2778d005-cc14-4e58-9bf2-3fc37bffb62f",
            "custom": "c6d8554c-8cb6-4d0b-aaaf-4ac19cea57de"
        },
        "ISU": {
            "sportsradar": "0e4258fa-3154-4c16-b693-adecab184c6c",
            "custom": "f40f4d56-d437-4957-a74e-6077081d0792"
        },
        "MISS": {
            "sportsradar": "d7d668ec-edaa-4d6b-be25-2ebba4128643",
            "custom": "55d426b3-34b3-462d-9bc3-6d4c61951e81"
        },
        "YALE": {
            "sportsradar": "ca478771-aa3d-4231-81e0-b70f519134fb",
            "custom": "e4b207d9-6684-43e4-b239-591a27561f96"
        },
        "TTU": {
            "sportsradar": "f8c705b7-87d3-411a-9c8b-5124daab0469",
            "custom": "01a80f3b-b32f-4d9e-9702-c839d27cff7b"
        },
        "UCLA": {
            "sportsradar": "ec0d6b67-4b16-4b50-92b2-1a651dae6b0f",
            "custom": "5265a362-6bfd-4ad0-a5bf-b196bc5b3672"
        },
        "NDSU": {
            "sportsradar": "984e7518-e418-45d5-9797-979b8c2085c1",
            "custom": "8d8b3a21-e5bf-45ac-bab7-1e010e425873"
        },
        "ARK": {
            "sportsradar": "c70c23c4-ab09-4797-a1af-792c848ab17f",
            "custom": "2a27b9af-edca-4c48-a7f0-0d76669aea36"
        },
        "MIA": {
            "sportsradar": "7aec5187-cb1b-45e5-8f7d-406d766cdc73",
            "custom": "80094ac0-d72b-4188-ba64-4c2c83f60c3d"
        },
        "MEM": {
            "sportsradar": "1551b3a0-6d10-4ffa-8dfa-73b56f004553",
            "custom": "c1e029fa-b200-4900-b151-1bfb1fb4cb43"
        },
        "MRSH": {
            "sportsradar": "58d8baa3-7624-4b21-a47f-a23df2bf8859",
            "custom": "3ff353e2-c2ed-444b-84b7-24160f3961dc"
        },
        "CONN": {
            "sportsradar": "efba5350-79bc-47aa-a189-db177b95b491",
            "custom": "5bc39948-a55d-4504-90fb-b5909108b5db"
        },
        "NW": {
            "sportsradar": "4b7dedc0-7b48-49a4-aad6-8a94a33274d2",
            "custom": "4e344d4a-9e86-42e5-a92d-0fe3fc9c2f8c"
        },
        "AUB": {
            "sportsradar": "0c0608b3-f349-4f5e-9a10-7e6a744dd0d2",
            "custom": "88456c37-ca0b-437b-96f0-c1508f64e27c"
        },
        "WVU": {
            "sportsradar": "f770d3a2-221c-49ce-9c7a-680f7417fe9e",
            "custom": "d2deecb0-0b2e-4c2c-86cf-74af64533ad6"
        },
        "CREI": {
            "sportsradar": "7d797407-623e-476d-b299-46de4275414d",
            "custom": "43c84be1-ff47-4870-944b-165af7c9ed64"
        },
        "JOES": {
            "sportsradar": "f9e4261e-d11d-46c4-bd33-c7bbc94ef0e8",
            "custom": "46f93244-a089-46c1-94ed-e82b3a29d88d"
        },
        "STAN": {
            "sportsradar": "683ab61f-546f-44da-b085-c3a5740554aa",
            "custom": "0affca0b-5955-47d6-b1f0-0841b1bae82d"
        },
        "VILL": {
            "sportsradar": "4383eb6a-7fd8-4ff2-94c5-43c933121e88",
            "custom": "9009a65c-e9b8-40d3-99de-57ccaaae4ee2"
        },
        "SJU": {
            "sportsradar": "c1f4aae1-aa16-4095-aeab-10e5c2a1236a",
            "custom": "4791083b-44b8-4677-ac09-4680e97b2fa9"
        },
        "IOWA": {
            "sportsradar": "c10544de-e3bd-4776-ba2e-83df8c017fd1",
            "custom": "aa58a788-d939-4ce5-8242-920204aa1674"
        },
        "CLEM": {
            "sportsradar": "dcf5c2e7-c227-4c20-af26-715d5f859412",
            "custom": "34f43d9e-9dcd-4769-b075-153d653f2ce0"
        },
        "BAY": {
            "sportsradar": "db6e1cab-3fa3-4a93-a673-8b2a358ff4bf",
            "custom": "ff932ba9-b086-4b31-8f34-efe485214243"
        },
        "UNC": {
            "sportsradar": "e9ca48b2-00ba-41c0-a02b-6885a2da1ff1",
            "custom": "db20eaba-2856-48c6-a790-5cbba7b29895"
        },
        "TEM": {
            "sportsradar": "8598d1b6-106b-4083-a512-2e495729525a",
            "custom": "b0983e9f-36f4-44dd-b68c-75ee2050d18a"
        },
        "UTAH": {
            "sportsradar": "0d037a5d-827a-44dd-8b70-57603d671d5d",
            "custom": "966dee87-0e52-4cb0-8bed-3022fd11db30"
        },
        "BUT": {
            "sportsradar": "bdb7d7a4-45f8-4bf3-ab85-15488c451494",
            "custom": "005446c6-ed83-4fd9-9c7e-67c7f492e077"
        },
        "MINN": {
            "sportsradar": "fa416692-7e09-4f0a-9bcf-0cf7d5149a14",
            "custom": "347d6c48-347d-4f6f-9a60-778132d817c6"
        },
        "TEX": {
            "sportsradar": "6ed15092-2670-450a-99c2-61d861e87644",
            "custom": "bb33fb75-a6ba-4b4a-9ea3-f8caddcc7f13"
        },
        "HOU": {
            "sportsradar": "1f99a164-d593-4d81-85d5-0d7889d6f486",
            "custom": "53f9dc00-e140-4c29-a187-576d2e2fce7e"
        },
        "VCU": {
            "sportsradar": "c1c1e6df-a383-4fbd-ba7b-32d4f9ef9518",
            "custom": "718dc513-1a35-4b39-a47c-997c0d0d3160"
        },
        "BYU": {
            "sportsradar": "c31455b2-8a45-4248-aa8f-ce7eab1c6b02",
            "custom": "306156d2-24f6-4c98-b736-956310cae924"
        },
        "MARQ": {
            "sportsradar": "06f7c904-0ac7-4125-b0f4-f4871bb69057",
            "custom": "74f1850a-c720-4526-bf9b-22c8be540a07"
        },
        "TXAM": {
            "sportsradar": "ef184799-d79b-49d9-a662-991eaf4044cd",
            "custom": "83e53f8d-0d20-48a1-bc63-cd11ed64e58f"
        },
        "LSU": {
            "sportsradar": "70e2bedd-3a0a-479c-ac99-e3f58aa6824b",
            "custom": "f60304bc-0564-4f5d-8f69-786eddddcc72"
        },
        "KU": {
            "sportsradar": "fae4855b-1b64-4b40-a632-9ed345e1e952",
            "custom": "08ec8920-9ce1-49ba-a48f-6d8420f37906"
        },
        "MICH": {
            "sportsradar": "bdc2561d-f603-4fab-a262-f1d2af462277",
            "custom": "27df3e56-88fd-4537-9fcb-a10059de616e"
        },
        "WAKE": {
            "sportsradar": "4fbebf0a-e117-4a0c-8f15-c247535a2a1b",
            "custom": "e7fc4e79-5b1e-429f-adda-c776a768aa6b"
        },
        "GONZ": {
            "sportsradar": "2f4d21f8-6d5f-48a5-abca-52a30583871a",
            "custom": "824f2ccf-64f1-4d26-9ba7-9c3040f85af8"
        },
        "LOU": {
            "sportsradar": "b795ddbc-baab-4499-8803-52e8608520ab",
            "custom": "9c8c3410-68a2-4843-8aea-63f3074bb61e"
        },
        "MSU": {
            "sportsradar": "a41d5a05-4c11-4171-a57e-e7a1ea325a6d",
            "custom": "42172061-4e86-43bc-a85e-6c1fd42d6af1"
        },
        "PSU": {
            "sportsradar": "4aebd148-8119-4875-954c-66779867989b",
            "custom": "00aebd9c-f70f-45c7-ba90-523bb85932ae"
        },
        "FSU": {
            "sportsradar": "d3c8a767-b6fc-45d4-a5f2-18406f2993f1",
            "custom": "8a328fb0-fc86-4da9-a206-09fe9ccbe00a"
        },
        "NEV": {
            "sportsradar": "62a73b4a-e281-4483-a1f8-f1160a18e456",
            "custom": "debcbf36-b60c-4e42-b058-5a4a05cfcfbb"
        },
        "LIB": {
            "sportsradar": "559db90c-741f-40d1-aa81-3fdd1d4889f3",
            "custom": "b201f92a-a974-4cf9-a9d8-1d6b4cd67b08"
        },
        "WIS": {
            "sportsradar": "c7569eae-5b93-4197-b204-6f3a62146b25",
            "custom": "2031d9cc-cc9f-4d7b-9ce9-49b75d54850b"
        },
        "ECU": {
            "sportsradar": "a601205f-3bfe-4052-ac0b-b8f18cf3efd3",
            "custom": "14a23f14-5bbc-4441-bada-44c989e163ec"
        },
        "SCU": {
            "sportsradar": "28023973-1d9d-4d01-b939-dc8f9b44fb1c",
            "custom": "dbd9d491-e8fb-4f44-a857-c79e9d4bc261"
        },
        "KSU": {
            "sportsradar": "d203f38a-a166-4258-bca2-e161b591ecfb",
            "custom": "2744f29c-9c2f-4267-9475-99abcc9249c0"
        }
    },
    "prospect": {
        "Brice Williams": {
            "sportsradar": "f5469bdd-f8a8-4516-b89a-9cd2134f2d5c",
            "custom": "eb322b2d-3197-4a42-9f25-1a949c2361e8"
        },
        "Jalon Moore": {
            "sportsradar": "38d718e1-7808-4d19-8b83-f7773ad8f90c",
            "custom": "adac4b18-603a-4ded-96e6-a9819e49291c"
        },
        "Tamar Bates": {
            "sportsradar": "65c99219-9190-4c9a-8cf3-3124a3c7a91e",
            "custom": "ee053f1f-dbfd-4c4e-bdff-887a0a7070b8"
        },
        "Grant Nelson": {
            "sportsradar": "8bb68b9b-4d9b-4f77-a683-90415894dcc6",
            "custom": "36184537-f920-42f0-9920-e9e7dc488d00"
        },
        "Jaxson Robinson": {
            "sportsradar": "4a79b58f-ba9c-4433-85f6-94c4101fb5b6",
            "custom": "28815bc9-ebd0-4f15-9fd3-05c12ec4d641"
        },
        "Dink Pate": {
            "sportsradar": "a9d3f9f1-480c-4a8c-905c-4d9b24080f55",
            "custom": "a0c709c7-7afe-41da-af2b-30f872994437"
        },
        "Izan Almansa": {
            "sportsradar": "f0c5e124-903d-490f-95d7-82d26fe9a43b",
            "custom": "e607103f-6cf5-4134-acf4-082229608388"
        },
        "Igor Milicic Jr.": {
            "sportsradar": "e19d4e5c-2001-4ddb-8ea7-d477f85279f7",
            "custom": "2f461c35-b41b-4906-aa65-370f3dc72cda"
        },
        "Malique Lewis": {
            "sportsradar": "4194d133-82d6-4fce-997b-404dbf71cd12",
            "custom": "e1840341-63d9-4a0a-b87d-962d178d864a"
        },
        "Noa Essengue": {
            "sportsradar": "27e573ba-e599-4720-bcbc-db742501872a",
            "custom": "c0036738-71ca-4fa9-ad8b-836c5efcd818"
        },
        "Walter Clayton Jr.": {
            "sportsradar": "090bb0d6-0eea-4d46-a8c9-c40dcd4099b4",
            "custom": "3eef473a-b3b0-4af1-9b49-f38db1f18da9"
        },
        "Hansen Yang": {
            "sportsradar": "aa5ecb74-2c86-40d2-8ea3-f1a570d17d80",
            "custom": "e344fed0-237c-4c76-b607-b8a8e4a9ff7e"
        },
        "Asa Newell": {
            "sportsradar": "4f58951c-d813-437a-8363-973268b93d06",
            "custom": "52f544ef-7076-4104-a28d-7195e884b2c7"
        },
        "Carter Bryant": {
            "sportsradar": "207a3201-6e1e-4aae-8e8e-e3fdff2b92fc",
            "custom": "bb9e3093-ab80-4187-bd9b-dcc873484eb6"
        },
        "Collin Murray-Boyles": {
            "sportsradar": "74bd291c-bbed-47a5-8979-83c48e5186c7",
            "custom": "e06bc7ea-f283-4cc1-b44a-cb57a38df947"
        },
        "Dylan Harper": {
            "sportsradar": "476b1087-8c07-4943-846c-0d28ceee8a49",
            "custom": "2a859511-76b0-4b45-9fec-f5185644ed04"
        },
        "Nolan Traore": {
            "sportsradar": "1d41aa95-d2fa-4dd8-a72a-298f986d2335",
            "custom": "005e3651-9fd6-40c3-8216-6a5ca0141ac7"
        },
        "Kon Knueppel": {
            "sportsradar": "cb479b71-e703-49d5-b59c-bd903a511c32",
            "custom": "cb68df58-4fcd-4c9a-82bd-6757b0332baa"
        },
        "Kasparas Jakucionis": {
            "sportsradar": "0707fbc4-4314-4a1e-915e-110720b23063",
            "custom": "8570173d-6677-4425-8342-21edeea847dc"
        },
        "Cooper Flagg": {
            "sportsradar": "f2f557f4-a1d2-4ad0-a4a9-dfa730b44699",
            "custom": "42015e2c-4bdb-4309-86a0-68d08d88a31f"
        },
        "Joan Beringer": {
            "sportsradar": "0ee8e914-87fd-48de-b378-a04a7352ab65",
            "custom": "d4329f44-d60a-4956-a5dd-56f508d54a6b"
        },
        "Nique Clifford": {
            "sportsradar": "f41dd443-8f9c-4302-bbcd-231c633e56a1",
            "custom": "04678d6a-c464-4139-a76f-eb295ed752f0"
        },
        "Thomas Sorber": {
            "sportsradar": "b27595b9-a7b1-4c1f-9c40-61485e8d1077",
            "custom": "9bb7b11e-4d65-4b26-950f-f920105385cd"
        },
        "Derik Queen": {
            "sportsradar": "c0fe1c0f-51e1-4e50-be22-4aadf61d6aba",
            "custom": "ee7298ba-51e1-4239-984c-c9f72fbd218b"
        },
        "Curtis Jones": {
            "sportsradar": "e009d9da-d248-4e3b-806a-45304e38ff4a",
            "custom": "742cd7e9-9a1e-4b4b-8d6c-3e7aea7d17c9"
        },
        "Sean Pedulla": {
            "sportsradar": "4151cbf1-e8c9-4f5c-b46b-39d236343cf3",
            "custom": "850e8238-8bb0-4731-8254-7f0a12624842"
        },
        "John Poulakidas": {
            "sportsradar": "93c8efd3-61fa-4fd0-8a57-f073b066df8f",
            "custom": "f1d46e9a-6ce4-4bb7-8d16-83b74a7313b8"
        },
        "Chance McMillian": {
            "sportsradar": "3cf73291-8dcd-4bf4-826d-13ce881349e9",
            "custom": "27e83e48-3f42-4ee2-8941-1abde110f0f6"
        },
        "Kobe Johnson": {
            "sportsradar": "0a4563ee-8ed1-417a-ae5d-4d0b86dca4e6",
            "custom": "b83f210f-eaf7-4c5e-a09d-242db6453b68"
        },
        "Jacksen Moni": {
            "sportsradar": "ed309be1-1433-41b9-80a4-3e7be3f24770",
            "custom": "45e8e9bd-b827-4679-a90c-2766ed171caa"
        },
        "Johnell Davis": {
            "sportsradar": "f666ce0a-1f90-4a76-96da-65b801a8bb19",
            "custom": "c7cbd89d-1dd7-4d42-97d9-7aca5597feda"
        },
        "Matthew Cleveland": {
            "sportsradar": "61546875-06b1-4d69-9b60-9f92577b3c4b",
            "custom": "9a197a64-6291-42a2-9089-2f476662f1bc"
        },
        "Tyrese Hunter": {
            "sportsradar": "58ac9124-b1bc-47de-bfb9-b5222014fbe6",
            "custom": "9a4e9209-a612-4789-8151-b51f19d82d4b"
        },
        "Obinna Anochili-Killen": {
            "sportsradar": "b0092ff2-3952-4c9f-a731-a12bf9f9377f",
            "custom": "4bd6a8ed-caaa-4dbb-b99b-0a6e80c7e740"
        },
        "Julian Reese": {
            "sportsradar": "3026d543-7b19-44c4-add7-07f48d21dc7c",
            "custom": "26f449c5-5054-4113-8d7d-e05b07de597a"
        },
        "Samson Johnson": {
            "sportsradar": "589fd0b7-d5ca-49ab-8514-91e71aea25d5",
            "custom": "ae0af57d-e73d-484a-bba9-9291880d2dd7"
        },
        "Andrew Carr": {
            "sportsradar": "48d10aed-76e2-4233-a423-ea92c37c2682",
            "custom": "416e58dc-b2b9-4ade-834c-4f0d17db6237"
        },
        "Noah Penda": {
            "sportsradar": "4294d984-a912-47e1-8d57-f0928d675651",
            "custom": "dea8a340-b167-48b2-bde7-fb3dd3283849"
        },
        "Saliou Niang": {
            "sportsradar": "a8389c77-929c-416b-b7b8-872415be8099",
            "custom": "dcfc0d04-18fc-4d3e-b5c8-630d4cb2c4c8"
        },
        "Brooks Barnhizer": {
            "sportsradar": "f42f9cb7-411f-43a2-ad48-2281b363d192",
            "custom": "feefdf20-a6f1-4975-92ea-c0de7acbb5fd"
        },
        "Johni Broome": {
            "sportsradar": "0c0b01bf-b446-497d-952b-bf052a1e1650",
            "custom": "20e12b8a-c395-4180-a28d-cc1915f63543"
        },
        "Alex Toohey": {
            "sportsradar": "f67afda4-7b10-4666-9f68-a32f940f398c",
            "custom": "a4552139-7bb7-4c47-b900-f5e692d26146"
        },
        "Javon Small": {
            "sportsradar": "dc4dbde0-f33c-4009-a577-1e7d1b916362",
            "custom": "4c3680a7-e067-489c-8d86-75fcc755dd66"
        },
        "Amari Williams": {
            "sportsradar": "a16c0c13-05e3-461a-acf2-c430939d808f",
            "custom": "9c296463-1d8b-44ce-be0d-7b19c8f6514c"
        },
        "Ryan Kalkbrenner": {
            "sportsradar": "b24ebe45-ad79-4a6c-91cc-35109b7c3d80",
            "custom": "a543743a-9d2a-40ee-a402-4647f531121f"
        },
        "Rasheer Fleming": {
            "sportsradar": "7213f637-1ad1-45e9-b849-65da068e9cac",
            "custom": "78a2e115-cd91-4222-a4c8-5d6e8bf36aa6"
        },
        "Maxime Raynaud": {

In [9]:
import pandas as pd
df = pd.DataFrame(college_teams)
df.head()

,team_id,team_alias,team_name,team_market,division_id,division_alias,division_name,conference_id,conference_alias,conference_name
0,ea0268d0-f801-4f83-ba8f-a4eb25898e04,NEB,Cornhuskers,Nebraska,248bff3e-84cf-4317-897d-fe27e608b6c7,D1,NCAA Division I,949bed95-58b2-40ff-ac1c-1c0c859bbb06,BIG10,Big Ten
1,da328854-c2b3-4d17-9c6e-9a2de66df143,OKLA,Sooners,Oklahoma,248bff3e-84cf-4317-897d-fe27e608b6c7,D1,NCAA Division I,00d87edf-9096-4b6e-aaca-8f642801ebc1,SEC,Southeastern
2,0be7fdae-0f70-4188-8499-ef08792308b8,MIZZ,Tigers,Missouri,248bff3e-84cf-4317-897d-fe27e608b6c7,D1,NCAA Division I,00d87edf-9096-4b6e-aaca-8f642801ebc1,SEC,Southeastern
3,f844b44a-2305-49f9-b591-e283ad4dafe0,ALA,Crimson Tide,Alabama,248bff3e-84cf-4317-897d-fe27e608b6c7,D1,NCAA Division I,00d87edf-9096-4b6e-aaca-8f642801ebc1,SEC,Southeastern
4,2c7d0198-54d7-475f-9224-6960e8e7aba7,UK,Wildcats,Kentucky,248bff3e-84cf-4317-897d-fe27e608b6c7,D1,NCAA Division I,00d87edf-9096-4b6e-aaca-8f642801ebc1,SEC,Southeastern

In [10]:
df.conference_name.value_counts()

conference_name
Southeastern         34
Big Ten              18
Atlantic Coast       15
Big 12               12
Big East             10
West Coast            3
American Athletic     3
Mountain West         2
Atlantic 10           2
Summit League         1
Ivy                   1
Sun Belt              1
Conference USA        1
Name: count, dtype: int64

In [13]:
# debug.prettyprint(dh, ensure_ascii=False)
list(dh)

dh_df = pd.DataFrame(dh['resultSets'][0]['rowSet'], columns=dh['resultSets'][0]['headers'])
dh_df.SEASON = dh_df.SEASON.astype(int)
subset = dh_df[dh_df.SEASON >= 1000]

In [14]:
team_columns = ['TEAM_ID', 'TEAM_CITY', 'TEAM_NAME', 'TEAM_ABBREVIATION']
organization_columns = ['ORGANIZATION', 'ORGANIZATION_TYPE']
draft_columns = [
    'PERSON_ID', 'PLAYER_NAME', 'SEASON', 'ROUND_NUMBER', 'ROUND_PICK', 'OVERALL_PICK', 
    *team_columns, *organization_columns
]
draft_subset = subset[draft_columns]
draft_subset

,PERSON_ID,PLAYER_NAME,SEASON,ROUND_NUMBER,ROUND_PICK,OVERALL_PICK,TEAM_ID,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,ORGANIZATION,ORGANIZATION_TYPE
0,1642843,Cooper Flagg,2025,1,1,1,1610612742,Dallas,Mavericks,DAL,Duke,College/University
1,1642844,Dylan Harper,2025,1,2,2,1610612759,San Antonio,Spurs,SAS,Rutgers,College/University
2,1642845,VJ Edgecombe,2025,1,3,3,1610612755,Philadelphia,76ers,PHI,Baylor,College/University
3,1642851,Kon Knueppel,2025,1,4,4,1610612766,Charlotte,Hornets,CHA,Duke,College/University
4,1642846,Ace Bailey,2025,1,5,5,1610612762,Utah,Jazz,UTA,Rutgers,College/University
...,...,...,...,...,...,...,...,...,...,...,...,...
8369,79320,Bob Jake,1947,0,0,0,1610610024,Baltimore,Bullets,BAL,Vermont,College/University
8370,79322,Charles Raynor,1947,0,0,0,1610610024,Baltimore,Bullets,BAL,Houston,College/University
8371,79323,John Rusinko,1947,0,0,0,1610610024,Baltimore,Bullets,BAL,Penn State,College/University
8372,76773,Harry Gallatin,1947,0,0,0,1610610024,Baltimore,Bullets,BAL,Truman State,College/University
8373,79284,Jack Stone,1947,0,0,0,1610610025,Chicago,Stags,CHS,Kansas State,College/University

In [ ]:
draft_subset.ORGANIZATION.value_counts()

In [ ]:
debug.prettyprint(id_mapper.ids, ensure_ascii=False)

In [ ]:
import os
import requests
from dotenv import load_dotenv

load_dotenv()
bearer = os.environ['CFBD_API_KEY']
header = {'Authorization': f'Bearer {bearer}'}
url = 'https://api.collegebasketballdata.com/teams'
rsp = requests.get(url, headers=header)
rsp.status_code

In [ ]:
y = rsp.json()

In [ ]:
y = pd.DataFrame(y)

In [ ]:
xs = set(x.shortName.str.lower().values)
ds = set(df.conference_name.str.lower().values)
len(xs), len(ds), len(xs.intersection(ds))

In [ ]:
ds.difference(xs)

In [ ]:
c = disk.read_json('data/college/college2.json')

In [ ]:
ct = []
for division in c['divisions']:
    for conference in division['conferences']:
        for team in conference['teams']:
            ct.append({
                'team_name': team['name'],
                'team_alias': team['alias'],
                'team_market': team['market'],
                'division_name': division['name'],
                'division_alias': division['alias'],
                'conference_name': conference['name'],
                'conference_alias': conference['alias'],
            })

In [ ]:
ct = pd.DataFrame(ct)

In [ ]:
xss = set(draft_subset.ORGANIZATION.str.lower())
yss = set(ct.team_market.str.lower())
len(xss), len(yss), len(xss.intersection(yss))

In [ ]:
draft_subset

In [ ]:
xss.difference(yss)

In [ ]:
gids = disk.read_json('data/unique_game_ids.json')
gids = gids[-1]['data']
gids = pd.DataFrame(gids)

In [ ]:
gids

In [ ]:
url = 'https://cdn.nba.com/static/json/liveData/boxscore/boxscore_0022000181.json'
rsp = requests.get(url)
rsp.status_code

In [ ]:
dict(rsp.headers)

In [ ]:
tmp = disk.read_json('data/nba/tmp.json')

In [ ]:
disk.write_json('data/nba/tmp.json', tmp)

In [23]:
header_contents = """
accept
*/*
accept-encoding
gzip, deflate, br, zstd
accept-language
nb-NO,nb;q=0.9,no;q=0.8,nn;q=0.7,en-US;q=0.6,en;q=0.5
cache-control
no-cache
cookie
mediakindauth2token=AuthToken1fZDLbtswFES_xtoUFsSnyIUWQuJHUrhPF0G7KWjy2iYskSpJxXa_vpITt0iRFiAuiZkzl8DUvbHgNFT7lLo4IfUEz4cToDlbt-tUSOe8C96o3G1Unh6Jbnxvcu3bgcruYuwh_JWNKf4nMrJ_UL2HVsX81DbRqy73YTeoxzgMXBRsuC7DGnDJpvPw1I2y7eg71UK16yGm7wa2qm9StvYHcOtzB9Vi1LM1OOXSnamuwC08Wg0X4gE2Wd00_gjmisXf3JcIYYi93F5r7fvLupf67dP9auYTqKatduAgDB870w9QfL2C1urgo9-m56KuJYixBP6PEoJvnkt4M67O6j7tfbA_VbLerVQ8VIQIVEpRFCUTnFGJOOeMMymxKIkUo4swFwQVSGBGMZKc0lIwyRBjBR0pKigrJRcMYy4Z4XjwC5HNTp0NEN-7CpWloMWgF9lNAJXAPImsxKORvYXzorem0gYVDEkz5eWWTalkaiqoVFNEStC65EC0ypar-ubzssaMV2zJrTuR7sPq3hv8rjt8my24P-wf9PzrVn28p4pO8OYHzGdHQifE_AI; nbatag_main_v_id=019d71a08e8c0021001940bbf3e60506f0019067019c0; OptanonAlertBoxClosed=2026-04-09T11:13:49.151Z; eupubconsent-v2=CQiZB7AQiZB7AAcABBENCZFsAP_gAAAAACiQMSgB4CIEQSFBACJwAIoAAAAEQAAAAEAAAAABAAAAAAAABAQAECAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAEgAAAABIAAAAAAAAAAAARKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATyff7Pn__rl_e7X_ve_n3zv8oXH77r____f_-7___2b_-___b-__7JoAAACQkAYACoAIIAZABoAEwAQgC8wgAIBR4DFh0AcABYAFQAQQAyADQAJgBFgF5jgAQBCAGLEIAIACyUAMABYATAF5kgAIDFikAcABYAFQAQQAyADQAJgBFgF5lAAIDFgAAA.f_wAAAAAAAAA.IMSwRYAFAAaABUADIAIAASAAqABaADIAGgAOgAigBJgCYAJwAWwAvgBhAD8AIAAQgApABlAEAAIQARYAjoBOwEagKPAXgAvMBiwDGQGfANmAbUA20Bt4DcwJwQTjBOYCdME7ATwgnkCfME-wUXgoyCjkFHgUmgpQClcFLQUvgpiCmQFNIKbAqJBUYFSYKlgqxBVoFXoKwAraBW8CuIFcwK7QV4BXoCvkFfgWJgsWCx8FkQXagu4DDMGGwYcgw8DEEGIgYjAxKAAA; at_check=true; s_ecid=MCMID%7C81492290038141589478614812525550188763; s_cc=true; AMCVS_248F210755B762187F000101%40AdobeOrg=1; __tld=nba.com; canPersist=true; AMCV_248F210755B762187F000101%40AdobeOrg=179643557%7CMCMID%7C81492290038141589478614812525550188763%7CMCAID%7CNONE%7CMCOPTOUT-1775762150s%7CNONE%7CvVersion%7C5.5.0%7CMCIDTS%7C20553%7CMCAAMLH-1776359750%7C6%7CMCAAMB-1776359750%7Cj8Odv6LonN4r3an7LhD3WZrU1bUpAkFkkiY1ncBR96t2PTI; _gid=GA1.2.470863044.1775754997; _ga_XQNG16PXVR=GS2.1.s1775754943$o1$g1$t1775755005$j60$l0$h0; _ga=GA1.2.2059718217.1775754944; _hjSessionUser_2837354=eyJpZCI6ImI1Yzg4MmFhLTc2OGYtNWQwZC04ZGRmLTM0ZTBjMjJiZTRkOSIsImNyZWF0ZWQiOjE3NzU3NTQ5NDg2ODIsImV4aXN0aW5nIjp0cnVlfQ==; bm_mi=CF07E3618B6A993993AB2F8A7CC2019F~YAAQXnchF/O4k2KdAQAABI5ldR/drkmM/Rjj/2IcNYZbVoU7bc9WSKReANtdK32kCaZzPaTR7s4xEpn0yx4icbh/+tUw30vcbkgw1Bd+a5ITz8tBmNfAOU28DAoWF68U9dcTLPhi4LSD17BAOYCqqmBL15pw9zw/OyWYCFMtAqwXypN/FGOMbvxbHPN5ZuWbsdkx4mYHXfXVt6yrWBJGoIEAlWMbVCyESS+FZjHJ0CDxKpBd8FQGDvZIePNP7afLOh0az6/wX36hGLNcb/WORvCvR3JRJu85ytOWBGshzgG+IKp5fqHM8JndHPPplR4=~1; nbatag_main__sn=7; nbatag_main_ses_id=1775791084179%3Bexp-session; nbatag_main_dc_visit=6; nbatag_main__ss=0%3Bexp-session; nbatag_main_dc_region=eu-central-1%3Bexp-session; ab.storage.deviceId.cf150dab-3153-49b0-b48c-66a7c18688ea=%7B%22g%22%3A%22a14abc75-c221-e8a4-aff0-92da6118005a%22%2C%22c%22%3A1775733229794%2C%22l%22%3A1775791084766%7D; AMP_MKTG_2442d50754=JTdCJTIycmVmZXJyZXIlMjIlM0ElMjJodHRwcyUzQSUyRiUyRnd3dy5nb29nbGUuY29tJTJGJTIyJTJDJTIycmVmZXJyaW5nX2RvbWFpbiUyMiUzQSUyMnd3dy5nb29nbGUuY29tJTIyJTdE; _abck=F7C1C43FA6297958E1CF4325D30CA083~0~YAAQXnchF/LZk2KdAQAAMdh9dQ9cgRRby2YJh3OZJS3u5SWWGcqlfchbwazOPT5wG+bdKg1D/WWvx/8uEVv/lLQO2ZVJ+haMzyf8ndo1hG34G+zyk7qhLBtfXfoRTZfFVPQicMX/buRtZFyiEKuNDMKNw4QMcsvEp5hUPm8Ca5EG3WFZmzXZt5U9WWuP0ohytf27wxYQGyYJrr4I0Xftj+P4wewIfxkzQlrhks3wmpQChVdAUE+hx1JOhJM/jW10KSnPqyzrXcyQmwAQrX2gSA7N324vZraLlg71r2Nt0le5soR3fJXOj+9qJ7riPCz2D5kyith1PRphVQ+o2INxllwX0X+3qkGuSmo+NPUxAAYBnT0sfGlYHgX6CNw4n1aVWCljqeR38ZtF4D0LM6KEit9MpCjB7aq7WYGiafm79dFPOAzKZ52iVhKop24iq36T7F/Wni5eBorYkD2h2z651RQEPoQQ5YSkeayZzOBHBSpkTRIecF+S42IvVtHMTZKdtBnyFVbG4ggSW4ySncYH5buXCO39LK6H6dDVOU4l5XtJvad4rdNzCSvSSh2XKJL4GGtuVYeDAm4kTbJS2O1XR18fDHUiG5gB8fkB2UNcNHQk/Kw/gJ6ivIM0HeLY1Th/uKhariIDddzu0UYtW1ZoxSqL7g5L1ZfS6eoLV35I92Tq7a1XlDpFWE0yM1aRUt9Fb1YDp9JuxxrFg2/cGJeZzhdmrmXLRWkstiHNVIJhDIkYiYe5q+GgycTEJGgyDW0FC3wSoLwoOks=~-1~-1~1775794683~AAQAAAAF%2f%2f%2f%2f%2fzi6Oro65XKwSRk1AVM6LDhBxMVqKRXr7T3LIAIA1tJQTnqI4TQfVhFSaXkqCMHZyqpGBG+n6INpDVa41WEJo0vWNUfByE3K8cOh5FXLcvu35DH+a8R9O%2fJVjouMl6zvTiOjHX4FtwLDN%2fMhmB2C9fZzJO5Kfxm7WR9ExPLORWiCbPe9detukfiEX2OT1RwtDG3DXvUtDPZooSjRTz6D30tEDNdX1BLQH74eGKz5XYkmIUM%3d~-1; iframeRef=www.nba.com/game/mem-vs-bkn-0021300908/game-charts; s_gpv_pageModal=nba%3Agames%3Agame-details%3Agame-charts; aaCustPrevPage=nba:games:game-details:game-charts; nbaOrigin=Page%20View%3A%20Game%20Details%20Box%20Score%7C%7CGames; _cs_mk_aa=0.549901771393414_1775792883513; bm_ss=ab8e18ef4e; bm_so=ED14246E7464DAC1E71C968467B9945A754F4570EF4D5F3AD62588A2E0C69063~YAAQXnchF9Dmk2KdAQAAtQ6FdQcKDcjEUzVBqYlksJXxJ/StBr1mU4ji/a0y27KW6USRYbrDVggaZB+2k0K7TgycqiKAIl7KkZi8Ghknm4FHdvhgnc4yim+hfyZcQZR6UlUA0oE6tkytVz+K4FsqtMqEBqQMy3SOo6lKwb8i7kSqerstuKTj3wB5gz+YEOl3wYNIl+7SWIyAtwGXMkRANXF18C121isOsEkFpK2NyEJj0APasiIJOeirLRqTinNStXM/HYjjvCJU5FmYrto0iLpjzK3eoJ69bD77az8NhTnT3wB+f/OQVfXp17Jyp/vgLN+Yd6EJdL+HY6qnRHXX5oQs7WaKIGgdCk+02lfj9VUxcouOSmSY5ulBViMjmUIeHgAZHYhlchYOw/t9EXYsE+6e4RO+WbXSCPib01P+MS7CVJ7I6Z3RqjWkuJe8yo7wRCK4BIrP1p5Ur/llTDiclIcojUIOewodYb1pmqiajSMIHeB1Pqzb; OptanonConsent=isGpcEnabled=0&datestamp=Fri+Apr+10+2026+05%3A52%3A28+GMT%2B0200+(Central+European+Summer+Time)&version=202511.1.0&browserGpcFlag=0&isIABGlobal=false&hosts=&consentId=f5564860-72ae-4a15-8ab6-602e8a51a37d&interactionCount=2&isAnonUser=1&landingPath=NotLandingPage&groups=dsa%3A1%2Ccad%3A1%2CNBAad%3A1%2Cmcp%3A1%2CNBAmt%3A1%2Cpad%3A1%2Cpap%3A1%2Cgld%3A1%2Cpcd%3A1%2Cpcp%3A1%2Cmap%3A1%2Cmra%3A1%2Cpdd%3A1%2Csid%3A1%2Csec%3A1%2Ctdc%3A1%2Ccos%3A1%2Cdlk%3A1%2Cdid%3A1%2Cdsh%3A1%2Cdsl%3A1%2Cven%3A1%2Creq%3A1&AwaitingReconsent=false&intType=1&geolocation=NO%3B03; nbatag_main__pn=9%3Bexp-session; nbatag_main__se=22%3Bexp-session; nbatag_main__st=1775794948815%3Bexp-session; s_ips=1304; s_ppv=nba%253Agames%253Agame-details%253Agame-charts%2C29%2C29%2C1304%2C1%2C3; __gads=ID=9d31533db7910237:T=1775733229:RT=1775793148:S=ALNI_MbqHDWjDYMzIk1F-NyEdcVAxuMRkA; __gpi=UID=0000139a73d9ab7f:T=1775733229:RT=1775793148:S=ALNI_MbUBVKh9VfIsZqhwnOtLD4sZqN7xQ; __eoi=ID=1c65af6dd079bd46:T=1775733229:RT=1775793148:S=AA-AfjYaQbbstDhV2gY1e295P99o; nbatag_main_dc_event=22%3Bexp-session; ab.storage.sessionId.cf150dab-3153-49b0-b48c-66a7c18688ea=%7B%22g%22%3A%22a038162f-24a6-e827-720e-1163acb0f539%22%2C%22e%22%3A1775794949061%2C%22c%22%3A1775791084763%2C%22l%22%3A1775793149061%7D; AMP_2442d50754=JTdCJTIyZGV2aWNlSWQlMjIlM0ElMjIwMTlkNzFhMDhlOGMwMDIxMDAxOTQwYmJmM2U2MDUwNmYwMDE5MDY3MDE5YzAlMjIlMkMlMjJ1c2VySWQlMjIlM0ElMjIlMjIlMkMlMjJzZXNzaW9uSWQlMjIlM0ExNzc1NzkxMDg1OTYwJTJDJTIyb3B0T3V0JTIyJTNBZmFsc2UlMkMlMjJsYXN0RXZlbnRUaW1lJTIyJTNBMTc3NTc5MzE0OTk0MyUyQyUyMmxhc3RFdmVudElkJTIyJTNBMTQ1JTJDJTIycGFnZUNvdW50ZXIlMjIlM0EwJTdE; s_tp=4442; bm_lso=ED14246E7464DAC1E71C968467B9945A754F4570EF4D5F3AD62588A2E0C69063~YAAQXnchF9Dmk2KdAQAAtQ6FdQcKDcjEUzVBqYlksJXxJ/StBr1mU4ji/a0y27KW6USRYbrDVggaZB+2k0K7TgycqiKAIl7KkZi8Ghknm4FHdvhgnc4yim+hfyZcQZR6UlUA0oE6tkytVz+K4FsqtMqEBqQMy3SOo6lKwb8i7kSqerstuKTj3wB5gz+YEOl3wYNIl+7SWIyAtwGXMkRANXF18C121isOsEkFpK2NyEJj0APasiIJOeirLRqTinNStXM/HYjjvCJU5FmYrto0iLpjzK3eoJ69bD77az8NhTnT3wB+f/OQVfXp17Jyp/vgLN+Yd6EJdL+HY6qnRHXX5oQs7WaKIGgdCk+02lfj9VUxcouOSmSY5ulBViMjmUIeHgAZHYhlchYOw/t9EXYsE+6e4RO+WbXSCPib01P+MS7CVJ7I6Z3RqjWkuJe8yo7wRCK4BIrP1p5Ur/llTDiclIcojUIOewodYb1pmqiajSMIHeB1Pqzb~1775793151063; ak_bmsc=CAD8DB6E9BD11AAABEED71609463010A~000000000000000000000000000000~YAAQXnchF3vnk2KdAQAA2k+FdR+C3TPvBHlHSsYmaieymDLwVTlAFdiiTiwLfyIG+s9AGt4UElmtNAO39XK1837v5oQr2XKNcmG6Sok99I0xeN1zqM41SCA1LrdEoQxx6DTBu0nhSNL9nXg3VgkRcW1zzFgjQPdux+7hWsd6C2zX1Zuq2F1oM+H4duG+AwJV7xVVI55PW2W/8PyKkgdK0yOPtpqT0xH0Gb4BA0ikT3VeGVzVBbcToEjRTCEWqMqtek70LykB6tslsQyrjP3ovpGg45c8/cfEn96qoOzFybskLcONxtwR1ZvGJc8OgT4GVmXSn9VMSO8fLq8HaNnaJK2QB43/iUYQhD+U2B8LOqtOmJB1khQiVLZAckBzFK9yOd5JyrlyXGgNcs8RXRHyza1IrbLSa/hev+9Q+W0Yww2YF4tRcwqM9EySpmjm8epaPzp5U2ZQPTI6tEteEH9QBpWzO25kaoiSrUw3fkZUzxTRPNTgTvHiiDEDfGQ5I1Au+wwwFAXXV20cXw==; bm_s=YAAQXnchF3znk2KdAQAA20+FdQVbIm53nio3fO/YvHyErlX7FaCO3Sw26uD2uR9x6SuUHkzMDzRLv/zwmC83wsvjD2FTdLVlXU8sS2mpeimnjAxmUpKqOC+iV3iXj4HNtTwu8cw8vvTUr0UoTQZS5cljXhPh5Kerbd3xRXrWYXdwjMlX7x955jbLaSWql2Eb6v2hn64vbWqcCEdG7jL915fhB4FKk70fEJZSz0dvrUJn9kwQDenrV6C4jCeAEkYWYz5CTDxmDjP33WOkKb7ClaNNSMP7+O07WnPQfTHw+VcJto5VpQvJE6fMghejmTZhLPxWahV2qmtbDNdqczDD+9xvwl1/mq23nVb/SKkCVmWsAdKWywLej7Yyt5Efmpc8JhHx/Maq8yf8peefwdS8YSU/m72dz6DUf7scQjQrP9UQpNNybwzQwrhQ9IDVB1vnYvduMGMFAewjSuzhiZYH8Mhzqa+lNFNp1ciwnqEbW2zb8QQcu2XxxcKoe/NF5JU+f0LYacJoaSrdUQ1c7q9S5ZaRi42JDzJxnP/j8BOnIg+6WOsvdFSC0uXvXP48k3BfrM9Dm0zP++BidDQfqSXRuufQ03C/1g308BIeui7Xc42lstQvlyfCzLeSrSlYEoQohQu6YQhPMlhNFe7tX1n0gmFyXittwI1k6OznwCKyxOcaGRZ933gIS76DH4QpleT+YW1NJT59Tgnv7Ar8xO4kQ0deMUXLMQmv1zppi38qOMOKxC+XSRXGllPoJcRTj4jfuMK0EWPgXgW2lxsj9Aoq5fxrOzqEu4FT+lcWi2G6D0awd+5ykCUgLDiRk5UyPux1ROQisI6KWOA7AOdswJv0PwpikGu9rKpj4ieOJ2J7ZORVHiJw868dHZERI1ESgn4UlPmg6Xd5mtt0NVkE20YK71xqYB3H1RJxycax6YskFEXcywWWQWSioHrPiQcNQdLuPX3wDs+9VtXrAAX/HGW4PFvh96UXx6fvOenNVCDkNO1bjc5l7HvNkoL3y1s=; bm_sv=A234BD4DCCCBF7F480613BC4F4B4D628~YAAQXnchF33nk2KdAQAA20+FdR+jhyk3nHtiNFDobns89KfC/LOeLq4gFy9zwTDBctdYPM885c8AFdEvFKDPPeKhe7T96SR3FWOOF9PaYT4eNMoMMk15oSdxnEeVdfMYWW5CRTTAHkkdQ8c4vmrZvXDpy6X8GuIhsWTr2Wau8216mrN3PMJXvf4I3gGe8YhU9iApeJcRZBwvbEpMD5NCXK4IP38vcAOHdW19N2Df3YIojoMbdbVsqKOVSDc8uQ==~1; bm_sz=B50DBEF5E27D8777BCA40535DD907D51~YAAQXnchF37nk2KdAQAA20+FdR+6KWK8iG0rVZCjaa54/6VFEGXEmfMby28hIW97UFZL9JxmaYr4AKsHkTP3aPYo+WUagMWIeBBnqukxv8pTtUu4bw5lEbP0q9p2rO/tRjZ2BLZoEe35X/5bKC4Rcfqe2HekR7VPkyEtSn/RQt89KunBGtnECdsBjNNEAssGJqcqr7CjVzZ20xUuQognexthovA+LujBoX0o38L07Qs4lfueEhBoVbuAns5hrhDWRDy8GuyRClNGPSJI18oU289bNCmA3igddeOQbX0GnDisWRJcLaNvBWE8hcMu2j0p3Tsq/UVg2oUy9r60oo/C8CFPmCOzi8QY6RUJsI3tIHOem9A4s172Ht43DFenDKPpU5brE/pNcWi3MqiDwxgP/VZaZtispt7+QRQiDyIThiwo26bPfCj9NhD7wobcPI1qSbFpdZZRFMnilviIybmnUoYHxk2WFirTRBju9qHDr7AZ+Q/rF42ippbFEjRhDRW1aQ==~4277301~3552825
pragma
no-cache
referer
https://www.nba.com/game/mem-vs-bkn-0021300908/game-charts
sec-ch-ua
"Chromium";v="146", "Not-A.Brand";v="24", "Google Chrome";v="146"
sec-ch-ua-mobile
?0
sec-ch-ua-platform
"Windows"
sec-fetch-dest
script
sec-fetch-mode
no-cors
sec-fetch-site
same-origin
user-agent
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36
""".strip()

header_contents = """
accept
*/*
accept-encoding
gzip, deflate, br, zstd
accept-language
nb-NO,nb;q=0.9,no;q=0.8,nn;q=0.7,en-US;q=0.6,en;q=0.5
cache-control
no-cache
origin
https://www.nba.com
pragma
no-cache
priority
u=1, i
referer
https://www.nba.com/
sec-ch-ua
"Chromium";v="146", "Not-A.Brand";v="24", "Google Chrome";v="146"
sec-ch-ua-mobile
?0
sec-ch-ua-platform
"Windows"
sec-fetch-dest
empty
sec-fetch-mode
cors
sec-fetch-site
same-site
user-agent
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36
""".strip()

headers = {}
for idx, line in enumerate(header_contents.splitlines()):
    if idx % 2 == 0:
        key = line.strip()
    else:
        value = line.strip()
        headers[key] = value

In [ ]:
url = 'https://www.nba.com/game/mem-vs-bkn-0021300908/game-charts'
rsp = requests.get(url, headers=headers)
rsp.status_code

In [53]:
import requests
url = 'https://stats.nba.com/stats/playerindex?College=&Country=&DraftPick=&DraftRound=&DraftYear=&Height=&Historical=1&LeagueID=00&Season=2025-26&SeasonType=Regular%20Season&TeamID=0&Weight='
url = 'https://stats.nba.com/js/data/playermovement/NBA_Player_Movement.json'
url = 'https://stats.nba.com/stats/leaguegamelog?Counter=1000&DateFrom=&DateTo=&Direction=DESC&ISTRound=&LeagueID=00&PlayerOrTeam=P&Season=2024-25&SeasonType=Regular%20Season&Sorter=DATE'
rsp = requests.get(url, headers=headers)
rsp.status_code

200

In [44]:
x = {
    "name": "otFlat",
    "html": "PGRpdiBpZD0ib25ldHJ1c3QtYmFubmVyLXNkayIgY2xhc3M9Im90RmxhdCI+PGRpdiByb2xlPSJkaWFsb2ciPjxkaXYgY2xhc3M9Im90LXNkay1jb250YWluZXIiPjxkaXYgY2xhc3M9Im90LXNkay1yb3ciPjxkaXYgaWQ9Im9uZXRydXN0LWdyb3VwLWNvbnRhaW5lciIgY2xhc3M9Im90LXNkay1laWdodCBvdC1zZGstY29sdW1ucyI+PGRpdiBjbGFzcz0iYmFubmVyX2xvZ28iPjwvZGl2PjxkaXYgaWQ9Im9uZXRydXN0LXBvbGljeSI+PGgyIGlkPSJvbmV0cnVzdC1wb2xpY3ktdGl0bGUiPlRpdGxlPC9oMj48ZGl2IGlkPSJvbmV0cnVzdC1wb2xpY3ktdGV4dCI+dGl0bGU8YSBocmVmPSIjIj5wb2xpY3k8L2E+PC9kaXY+PGRpdiBjbGFzcz0ib3QtZHBkLWNvbnRhaW5lciI+PGgzIGNsYXNzPSJvdC1kcGQtdGl0bGUiPldlIGNvbGxlY3QgZGF0YSBpbiBvcmRlciB0byBwcm92aWRlOjwvaDM+PGRpdiBjbGFzcz0ib3QtZHBkLWNvbnRlbnQiPjxwIGNsYXNzPSJvdC1kcGQtZGVzYyI+ZGVzY3JpcHRpb248L3A+PC9kaXY+PC9kaXY+PC9kaXY+PC9kaXY+PGRpdiBpZD0ib25ldHJ1c3QtYnV0dG9uLWdyb3VwLXBhcmVudCIgY2xhc3M9Im90LXNkay10aHJlZSBvdC1zZGstY29sdW1ucyI+PGRpdiBpZD0ib25ldHJ1c3QtYnV0dG9uLWdyb3VwIj48YnV0dG9uIGlkPSJvbmV0cnVzdC1wYy1idG4taGFuZGxlciI+Y2hvaWNlPC9idXR0b24+IDxidXR0b24gaWQ9Im9uZXRydXN0LXJlamVjdC1hbGwtaGFuZGxlciI+UmVqZWN0PC9idXR0b24+IDxidXR0b24gaWQ9Im9uZXRydXN0LWFjY2VwdC1idG4taGFuZGxlciI+QWNjZXB0PC9idXR0b24+PC9kaXY+PC9kaXY+PC9kaXY+PC9kaXY+PGRpdiBjbGFzcz0ib3Qtc2RrLWNvbnRhaW5lciIgaWQ9ImJhbm5lci1vcHRpb25zIj48ZGl2IGNsYXNzPSJvdC1zZGstZm91ciBvdC1zZGstY29sdW1ucyBiYW5uZXItb3B0aW9uIj48YnV0dG9uIGFyaWEtZXhwYW5kZWQ9ImZhbHNlIiBjbGFzcz0iYmFubmVyLW9wdGlvbi1pbnB1dCI+PHNwYW4gY2xhc3M9ImJhbm5lci1vcHRpb24taGVhZGVyIj48aDQ+UHVycG9zZSB3ZSB1c2U8L2g0PjxzcGFuIGNsYXNzPSJvdC1hcnJvdy1jb250YWluZXIiPjwvc3Bhbj48L3NwYW4+PC9idXR0b24+PGRpdiBjbGFzcz0iYmFubmVyLW9wdGlvbi1kZXRhaWxzIj5wdXJwb3NlIGRlc2NyaXB0aW9uPC9kaXY+PC9kaXY+PC9kaXY+PCEtLSBDbG9zZSBCdXR0b24gLS0+PGRpdiBpZD0ib25ldHJ1c3QtY2xvc2UtYnRuLWNvbnRhaW5lciI+PGJ1dHRvbiBjbGFzcz0ib25ldHJ1c3QtY2xvc2UtYnRuLWhhbmRsZXIgb25ldHJ1c3QtY2xvc2UtYnRuLXVpIGJhbm5lci1jbG9zZS1idXR0b24gb3QtY2xvc2UtaWNvbiI+PC9idXR0b24+PC9kaXY+PCEtLSBDbG9zZSBCdXR0b24gRU5ELS0+PC9kaXY+PC9kaXY+",
    "css": "#onetrust-banner-sdk{box-shadow:0 0 18px rgba(0,0,0,.2)}#onetrust-banner-sdk.otFlat{position:fixed;z-index:2147483645;bottom:0;right:0;left:0;background-color:#fff;max-height:90%;overflow-x:hidden;overflow-y:auto}#onetrust-banner-sdk.otFlat.top{top:0px;bottom:auto}#onetrust-banner-sdk.otRelFont{font-size:1rem}#onetrust-banner-sdk>.ot-sdk-container{overflow:hidden}#onetrust-banner-sdk::-webkit-scrollbar{width:11px}#onetrust-banner-sdk::-webkit-scrollbar-thumb{border-radius:10px;background:#c1c1c1}#onetrust-banner-sdk{scrollbar-arrow-color:#c1c1c1;scrollbar-darkshadow-color:#c1c1c1;scrollbar-face-color:#c1c1c1;scrollbar-shadow-color:#c1c1c1}#onetrust-banner-sdk #onetrust-policy{margin:1.25em 0 .625em 2em;overflow:hidden}#onetrust-banner-sdk #onetrust-policy .ot-gv-list-handler{float:left;font-size:.82em;padding:0;margin-bottom:0;border:0;line-height:normal;height:auto;width:auto}#onetrust-banner-sdk #onetrust-policy-title{font-size:1.2em;line-height:1.3;margin-bottom:10px}#onetrust-banner-sdk #onetrust-group-container{position:relative}#onetrust-banner-sdk #onetrust-policy-text{clear:both;text-align:left;font-size:.88em;line-height:1.4}#onetrust-banner-sdk #onetrust-policy-text *{font-size:inherit;line-height:inherit}#onetrust-banner-sdk #onetrust-policy-text a{font-weight:bold}#onetrust-banner-sdk #onetrust-policy-title,#onetrust-banner-sdk #onetrust-policy-text{color:dimgray;float:left}#onetrust-banner-sdk #onetrust-button-group-parent{min-height:1px;text-align:center}#onetrust-banner-sdk #onetrust-button-group{display:inline-block}#onetrust-banner-sdk #onetrust-accept-btn-handler,#onetrust-banner-sdk #onetrust-reject-all-handler,#onetrust-banner-sdk #onetrust-pc-btn-handler{background-color:#68b631;color:#fff;border-color:#68b631;margin-right:1em;min-width:125px;height:auto;white-space:normal;word-break:break-word;word-wrap:break-word;padding:12px 10px;line-height:1.2;font-size:.813em;font-weight:600}#onetrust-banner-sdk #onetrust-pc-btn-handler.cookie-setting-link{background-color:#fff;border:none;color:#68b631;text-decoration:underline;padding-left:0;padding-right:0}#onetrust-banner-sdk .onetrust-close-btn-ui{width:44px;height:44px;background-size:12px;border:none;position:relative;margin:auto;padding:0}#onetrust-banner-sdk .banner_logo{display:none}#onetrust-banner-sdk.ot-bnr-w-logo .ot-bnr-logo{position:absolute;top:50%;transform:translateY(-50%);left:0px;margin-right:5px}#onetrust-banner-sdk.ot-bnr-w-logo #onetrust-policy{margin-left:65px}#onetrust-banner-sdk .ot-b-addl-desc{clear:both;float:left;display:block}#onetrust-banner-sdk #banner-options{float:left;display:table;margin-right:0;margin-left:1em;width:calc(100% - 1em)}#onetrust-banner-sdk .banner-option-input{cursor:pointer;width:auto;height:auto;border:none;padding:0;padding-right:3px;margin:0 0 10px;font-size:.82em;line-height:1.4}#onetrust-banner-sdk .banner-option-input *{pointer-events:none;font-size:inherit;line-height:inherit}#onetrust-banner-sdk .banner-option-input[aria-expanded=true]~.banner-option-details{display:block;height:auto}#onetrust-banner-sdk .banner-option-input[aria-expanded=true] .ot-arrow-container{transform:rotate(90deg)}#onetrust-banner-sdk .banner-option{margin-bottom:12px;margin-left:0;border:none;float:left;padding:0}#onetrust-banner-sdk .banner-option:first-child{padding-left:2px}#onetrust-banner-sdk .banner-option:not(:first-child){padding:0;border:none}#onetrust-banner-sdk .banner-option-header{cursor:pointer;display:inline-block}#onetrust-banner-sdk .banner-option-header :first-child{color:dimgray;font-weight:bold;float:left}#onetrust-banner-sdk .banner-option-header .ot-arrow-container{display:inline-block;border-top:6px solid rgba(0,0,0,0);border-bottom:6px solid rgba(0,0,0,0);border-left:6px solid dimgray;margin-left:10px;vertical-align:middle}#onetrust-banner-sdk .banner-option-details{display:none;font-size:.83em;line-height:1.5;padding:10px 0px 5px 10px;margin-right:10px;height:0px}#onetrust-banner-sdk .banner-option-details *{font-size:inherit;line-height:inherit;color:dimgray}#onetrust-banner-sdk .ot-arrow-container,#onetrust-banner-sdk .banner-option-details{transition:all 300ms ease-in 0s;-webkit-transition:all 300ms ease-in 0s;-moz-transition:all 300ms ease-in 0s;-o-transition:all 300ms ease-in 0s}#onetrust-banner-sdk .ot-dpd-container{float:left}#onetrust-banner-sdk .ot-dpd-title{margin-bottom:10px}#onetrust-banner-sdk .ot-dpd-title,#onetrust-banner-sdk .ot-dpd-desc{font-size:.88em;line-height:1.4;color:dimgray}#onetrust-banner-sdk .ot-dpd-title *,#onetrust-banner-sdk .ot-dpd-desc *{font-size:inherit;line-height:inherit}#onetrust-banner-sdk.ot-iab-2 #onetrust-policy-text *{margin-bottom:0}#onetrust-banner-sdk.ot-iab-2 .onetrust-vendors-list-handler{display:block;margin-left:0;margin-top:5px;clear:both;margin-bottom:0;padding:0;border:0;height:auto;width:auto}#onetrust-banner-sdk.ot-iab-2 #onetrust-button-group button{display:block}#onetrust-banner-sdk.ot-close-btn-link{padding-top:25px}#onetrust-banner-sdk.ot-close-btn-link #onetrust-close-btn-container{top:15px;transform:none;right:15px}#onetrust-banner-sdk.ot-close-btn-link #onetrust-close-btn-container button{padding:0;white-space:pre-wrap;border:none;height:auto;line-height:1.5;text-decoration:underline;font-size:.69em}#onetrust-banner-sdk #onetrust-policy-text,#onetrust-banner-sdk .ot-dpd-desc,#onetrust-banner-sdk .ot-b-addl-desc{font-size:.813em;line-height:1.5}#onetrust-banner-sdk .ot-dpd-desc{margin-bottom:10px}#onetrust-banner-sdk .ot-dpd-desc>.ot-b-addl-desc{margin-top:10px;margin-bottom:10px;font-size:1em}@media only screen and (max-width: 425px){#onetrust-banner-sdk #onetrust-close-btn-container{position:absolute;top:6px;right:2px}#onetrust-banner-sdk #onetrust-policy{margin-left:0;margin-top:3em}#onetrust-banner-sdk #onetrust-button-group{display:block}#onetrust-banner-sdk #onetrust-accept-btn-handler,#onetrust-banner-sdk #onetrust-reject-all-handler,#onetrust-banner-sdk #onetrust-pc-btn-handler{width:100%}#onetrust-banner-sdk .onetrust-close-btn-ui{top:auto;transform:none}#onetrust-banner-sdk #onetrust-policy-title{display:inline;float:none}#onetrust-banner-sdk #banner-options{margin:0;padding:0;width:100%}}@media only screen and (max-width: 550px){#onetrust-button-group.ot-button-order-container #onetrust-accept-btn-handler,#onetrust-button-group.ot-button-order-container #onetrust-reject-all-handler,#onetrust-button-group.ot-button-order-container #onetrust-pc-btn-handler{margin-right:0}#onetrust-banner-sdk .has-reject-all-button div#onetrust-button-group.ot-button-order-container #onetrust-accept-btn-handler,#onetrust-banner-sdk .has-reject-all-button div#onetrust-button-group.ot-button-order-container #onetrust-reject-all-handler,#onetrust-banner-sdk .has-reject-all-button div#onetrust-button-group.ot-button-order-container #onetrust-pc-btn-handler{margin-right:0}}@media only screen and (min-width: 426px)and (max-width: 896px){#onetrust-banner-sdk #onetrust-close-btn-container{position:absolute;top:0;right:0}#onetrust-banner-sdk #onetrust-policy{margin-left:1em;margin-right:1em}#onetrust-banner-sdk .onetrust-close-btn-ui{top:10px;right:10px}#onetrust-banner-sdk:not(.ot-iab-2) #onetrust-group-container{width:95%}#onetrust-banner-sdk.ot-iab-2 #onetrust-group-container{width:100%}#onetrust-banner-sdk.ot-bnr-w-logo #onetrust-button-group-parent{padding-left:50px}#onetrust-banner-sdk #onetrust-button-group-parent{width:100%;position:relative;margin-left:0}#onetrust-banner-sdk #onetrust-button-group button{display:inline-block}#onetrust-banner-sdk #onetrust-button-group{margin-right:0;text-align:center}#onetrust-banner-sdk #onetrust-button-group.ot-button-order-container #onetrust-accept-btn-handler,#onetrust-banner-sdk #onetrust-button-group.ot-button-order-container #onetrust-reject-all-handler,#onetrust-banner-sdk #onetrust-button-group.ot-button-order-container #onetrust-pc-btn-handler{width:auto}#onetrust-banner-sdk .has-reject-all-button #onetrust-button-group.ot-button-order-container{display:inline-flex;flex-wrap:wrap}#onetrust-banner-sdk .has-reject-all-button #onetrust-button-group.ot-button-order-container #onetrust-pc-btn-handler,#onetrust-banner-sdk .has-reject-all-button #onetrust-button-group.ot-button-order-container #onetrust-reject-all-handler,#onetrust-banner-sdk .has-reject-all-button #onetrust-button-group.ot-button-order-container #onetrust-accept-btn-handler{float:none}#onetrust-banner-sdk .has-reject-all-button #onetrust-button-group.ot-button-order-container *[class*=ot-button-order-]:nth-of-type(1){margin-right:auto !important}#onetrust-banner-sdk .has-reject-all-button #onetrust-pc-btn-handler{float:left}#onetrust-banner-sdk .has-reject-all-button #onetrust-reject-all-handler,#onetrust-banner-sdk .has-reject-all-button #onetrust-accept-btn-handler{float:right}#onetrust-banner-sdk .has-reject-all-button #onetrust-button-group{width:calc(100% - 2em);margin-right:0}#onetrust-banner-sdk .has-reject-all-button #onetrust-pc-btn-handler.cookie-setting-link{padding-left:0px;text-align:left}#onetrust-banner-sdk.ot-buttons-fw .ot-sdk-three button{width:100%;text-align:center}#onetrust-banner-sdk.ot-buttons-fw #onetrust-button-group-parent button{float:none}#onetrust-banner-sdk.ot-buttons-fw #onetrust-pc-btn-handler.cookie-setting-link{text-align:center}}@media only screen and (min-width: 550px){#onetrust-banner-sdk .banner-option:not(:first-child){border-left:1px solid #d8d8d8;padding-left:25px}}@media only screen and (min-width: 425px)and (max-width: 550px){#onetrust-banner-sdk.ot-iab-2 #onetrust-button-group,#onetrust-banner-sdk.ot-iab-2 .banner-option{width:100%}#onetrust-banner-sdk.ot-iab-2 #onetrust-button-group #onetrust-accept-btn-handler,#onetrust-banner-sdk.ot-iab-2 #onetrust-button-group #onetrust-reject-all-handler,#onetrust-banner-sdk.ot-iab-2 #onetrust-button-group #onetrust-pc-btn-handler{width:100%}#onetrust-banner-sdk.ot-iab-2 #onetrust-button-group #onetrust-accept-btn-handler,#onetrust-banner-sdk.ot-iab-2 #onetrust-button-group #onetrust-reject-all-handler{float:left}#onetrust-banner-sdk.ot-iab-2 #onetrust-button-group.ot-button-order-container{width:auto}}@media only screen and (min-width: 769px){#onetrust-banner-sdk #onetrust-button-group{margin-right:30%}#onetrust-banner-sdk #banner-options{margin-left:2em;margin-right:5em;margin-bottom:1.25em;width:calc(100% - 7em)}}@media only screen and (min-width: 897px)and (max-width: 1023px){#onetrust-banner-sdk.vertical-align-content #onetrust-button-group-parent{position:absolute;top:50%;left:80%;transform:translateY(-50%)}#onetrust-banner-sdk #onetrust-close-btn-container{top:50%;margin:auto;transform:translate(-50%, -50%);position:absolute;padding:0;right:0}#onetrust-banner-sdk #onetrust-close-btn-container button{position:relative;margin:0;right:-22px;top:2px}}@media only screen and (min-width: 1024px){#onetrust-banner-sdk #onetrust-close-btn-container{top:50%;margin:auto;transform:translate(-50%, -50%);position:absolute;right:0}#onetrust-banner-sdk #onetrust-close-btn-container button{right:-12px}#onetrust-banner-sdk #onetrust-policy{margin-left:2em}#onetrust-banner-sdk.vertical-align-content #onetrust-button-group-parent{position:absolute;top:50%;left:60%;transform:translateY(-50%)}#onetrust-banner-sdk .ot-optout-signal{width:50%}#onetrust-banner-sdk.ot-iab-2 #onetrust-policy-title{width:50%}#onetrust-banner-sdk.ot-iab-2 #onetrust-policy-text,#onetrust-banner-sdk.ot-iab-2 :not(.ot-dpd-desc)>.ot-b-addl-desc{margin-bottom:1em;width:50%;border-right:1px solid #d8d8d8;padding-right:1rem}#onetrust-banner-sdk.ot-iab-2 #onetrust-policy-text{margin-bottom:0;padding-bottom:1em}#onetrust-banner-sdk.ot-iab-2 :not(.ot-dpd-desc)>.ot-b-addl-desc{margin-bottom:0;padding-bottom:1em}#onetrust-banner-sdk.ot-iab-2 .ot-dpd-container{width:45%;padding-left:1rem;display:inline-block;float:none}#onetrust-banner-sdk.ot-iab-2 .ot-dpd-title{line-height:1.7}#onetrust-banner-sdk.ot-iab-2 #onetrust-button-group-parent{left:auto;right:4%;margin-left:0}#onetrust-banner-sdk.ot-iab-2 #onetrust-button-group button{display:block}#onetrust-banner-sdk:not(.ot-iab-2) #onetrust-button-group-parent{margin:auto;width:30%}#onetrust-banner-sdk:not(.ot-iab-2) #onetrust-group-container{width:60%}#onetrust-banner-sdk #onetrust-button-group{margin-right:auto}#onetrust-banner-sdk #onetrust-accept-btn-handler,#onetrust-banner-sdk #onetrust-reject-all-handler,#onetrust-banner-sdk #onetrust-pc-btn-handler{margin-top:1em}}@media only screen and (min-width: 890px){#onetrust-banner-sdk.ot-buttons-fw:not(.ot-iab-2) #onetrust-button-group-parent{padding-left:3%;padding-right:4%;margin-left:0}#onetrust-banner-sdk.ot-buttons-fw:not(.ot-iab-2) #onetrust-button-group{margin-right:0;margin-top:1.25em;width:100%}#onetrust-banner-sdk.ot-buttons-fw:not(.ot-iab-2) #onetrust-button-group button{width:100%;margin-bottom:5px;margin-top:5px}#onetrust-banner-sdk.ot-buttons-fw:not(.ot-iab-2) #onetrust-button-group button:last-of-type{margin-bottom:20px}}@media only screen and (min-width: 1280px){#onetrust-banner-sdk:not(.ot-iab-2) #onetrust-group-container{width:55%}#onetrust-banner-sdk:not(.ot-iab-2) #onetrust-button-group-parent{width:44%;padding-left:2%;padding-right:2%}#onetrust-banner-sdk:not(.ot-iab-2).vertical-align-content #onetrust-button-group-parent{position:absolute;left:55%}}"
}

In [45]:
import base64

def b64decode(data):
    return base64.b64decode(data).decode('utf-8')

html = b64decode(x['html'])
html

'<div id="onetrust-banner-sdk" class="otFlat"><div role="dialog"><div class="ot-sdk-container"><div class="ot-sdk-row"><div id="onetrust-group-container" class="ot-sdk-eight ot-sdk-columns"><div class="banner_logo"></div><div id="onetrust-policy"><h2 id="onetrust-policy-title">Title</h2><div id="onetrust-policy-text">title<a href="#">policy</a></div><div class="ot-dpd-container"><h3 class="ot-dpd-title">We collect data in order to provide:</h3><div class="ot-dpd-content"><p class="ot-dpd-desc">description</p></div></div></div></div><div id="onetrust-button-group-parent" class="ot-sdk-three ot-sdk-columns"><div id="onetrust-button-group"><button id="onetrust-pc-btn-handler">choice</button> <button id="onetrust-reject-all-handler">Reject</button> <button id="onetrust-accept-btn-handler">Accept</button></div></div></div></div><div class="ot-sdk-container" id="banner-options"><div class="ot-sdk-four ot-sdk-columns banner-option"><button aria-expanded="false" class="banner-option-input"><span class="banner-option-header"><h4>Purpose we use</h4><span class="ot-arrow-container"></span></span></button><div class="banner-option-details">purpose description</div></div></div><!-- Close Button --><div id="onetrust-close-btn-container"><button class="onetrust-close-btn-handler onetrust-close-btn-ui banner-close-button ot-close-icon"></button></div><!-- Close Button END--></div></div>'

In [54]:
j = rsp.json()

In [55]:
disk.write_json('data/_v2/leaguegamelog_24_25.json', j)

In [56]:
list(j)

['resource', 'parameters', 'resultSets']

In [57]:
a = j['resultSets'][-1]
a = pd.DataFrame(a['rowSet'], columns=a['headers'])
a

,SEASON_ID,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,...,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,FANTASY_PTS,VIDEO_AVAILABLE
0,22024,1628436,Luke Kornet,1610612738,BOS,Boston Celtics,0022401187,2025-04-13,BOS vs. CHA,W,...,8,2,1,4,0,2,11,1,38.6,1
1,22024,1630202,Payton Pritchard,1610612738,BOS,Boston Celtics,0022401187,2025-04-13,BOS vs. CHA,W,...,7,7,1,0,4,0,34,8,51.9,1
2,22024,202684,Tristan Thompson,1610612739,CLE,Cleveland Cavaliers,0022401189,2025-04-13,CLE vs. IND,L,...,20,1,1,2,3,3,3,-25,34.5,1
3,22024,1631288,Jamal Cain,1610612740,NOP,New Orleans Pelicans,0022401196,2025-04-13,NOP vs. OKC,L,...,4,1,1,0,1,4,18,-4,26.3,1
4,22024,1628989,Kevin Huerter,1610612741,CHI,Chicago Bulls,0022401191,2025-04-13,CHI @ PHI,W,...,2,2,0,0,0,2,18,4,23.4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26301,22024,1630574,Ariel Hukporti,1610612752,NYK,New York Knicks,0022400061,2024-10-22,NYK @ BOS,L,...,4,0,0,1,0,0,0,9,7.8,1
26302,22024,1631210,Jacob Toppin,1610612752,NYK,New York Knicks,0022400061,2024-10-22,NYK @ BOS,L,...,0,0,0,0,0,0,0,0,0.0,1
26303,22024,1642359,Pacôme Dadiet,1610612752,NYK,New York Knicks,0022400061,2024-10-22,NYK @ BOS,L,...,1,0,0,0,0,1,3,10,4.2,1
26304,22024,1629637,Jaxson Hayes,1610612747,LAL,Los Angeles Lakers,0022400062,2024-10-22,LAL vs. MIN,W,...,4,0,0,1,0,3,10,-1,17.8,1
26305,22024,1630162,Anthony Edwards,1610612750,MIN,Minnesota Timberwolves,0022400062,2024-10-22,MIN @ LAL,L,...,6,3,0,0,4,3,27,0,34.7,1

In [31]:
a.PERSON_ID.value_counts()

PERSON_ID
1628427    1
76001      1
76002      1
76003      1
51         1
          ..
1630173    1
203518     1
76007      1
76006      1
76005      1
Name: count, Length: 5126, dtype: int64

In [ ]:
from bs4 import BeautifulSoup
soup = BeautifulSoup(rsp.text, 'html.parser')

In [ ]:
from IPython.display import display, HTML

In [ ]:
contents = soup.find_all(attrs={'type': 'application/json'})

In [1]:
import json

json.loads(contents[0].text)

NameError: name 'contents' is not defined

In [5]:
import requests
from bs4 import BeautifulSoup

In [6]:
header_contents = """
accept
*/*
accept-encoding
gzip, deflate, br, zstd
accept-language
nb-NO,nb;q=0.9,no;q=0.8,nn;q=0.7,en-US;q=0.6,en;q=0.5
cache-control
no-cache
cookie
SWID=C14BDF1F-F1BF-4D0E-CDA7-AB4F6B41A5B9; OptanonAlertBoxClosed=2026-04-10T00:46:09.298Z; eupubconsent-v2=CQicU3AQicU3AAcABBENCZFgAAAAAEPgAChQAAAYiABMNDogjLIgUCBQEIIEACgrCACgQBAAAkDRAQAmDAhyBgAusJkAIAUAAwQAgABBgACAAASABCIAIACAQAgQCBQABgAQBAQAMDAAGACxEAgABAdAxTAggECwASIyqDTAlAASCAlsqEEoGBBXCFIscAggREwUAAAIABQAAID4WAhJKCViQQBcQXQAAEAAAUQIkCKQswBBUGaLQVgScBkaYBk-YJklOgyAJghIyDIhNUEg8UxRCghyA2KWYA6eIKAGXayQh_qAAAAA.YAAACHwAAAAA.IMStR_G__bXlv-bb36btkeYxf9_hr7sQxBgbJs24FzLvW7JwH32E7NEzatqYKmRIAu3TBIQNtHJjURUChKIgVrzDsaE2U4TtKJ-BkiHMZY2tYCFxvm4tjWQCZ4ur_51d9mT-t7dr-2dzy27hnv3a9fuS1UJidKYetHfv8ZBOT-_IU9_x-_4v4_MbpEm-eS1v_tWtt43d64vP_dpuxt-Tyff7____73_e7X__e__33_-qXX_77____________f__________9oAA; s_ecid=MCMID%7C86802923025445614922182749332434390880; userZip=1534; tveMVPDAuth=; _gcl_au=1.1.301185680.1775792131; tveAuth=; espn_aid=e6bc25f6-d240-4ce9-bd8d-d6debaf7961f; country=no; hashedIp=f59d3283d257c8367fe84395284b8f0cfa5626cd5840aff70f1329a2efe7870c; block.check=false%7Cfalse; espn-prev-page=espn%3Anba%3Agame%3Aboxscore; AMCVS_EE0201AC512D2BE80A490D4C%40AdobeOrg=1; AMCV_EE0201AC512D2BE80A490D4C%40AdobeOrg=-50417514%7CMCMID%7C86802923025445614922182749332434390880%7CMCAAMLH-1776401056%7C6%7CMCAAMB-1776401056%7C6G1ynYcLPuiQxYZrsz_pkqfLG9yMXBpb2zX5dvJdYQJzPXImdj0y%7CMCOPTOUT-1775803456s%7CNONE%7CMCAID%7CNONE%7CvVersion%7C5.5.0; s_cc=true; __eoi=ID=47428297a185a554:T=1775792131:RT=1775796257:S=AA-AfjbmjXeqfHnLkshSjZoku7Bq; s_ensNR=1775796614169-Repeat; OptanonConsent=isGpcEnabled=0&datestamp=Fri+Apr+10+2026+06%3A50%3A14+GMT%2B0200+(Central+European+Summer+Time)&version=202601.2.0&browserGpcFlag=0&isIABGlobal=false&identifierType=DeviceId&hosts=&consentId=71014b4a-9693-4aff-8378-db4fa126c9a0&interactionCount=1&isAnonUser=1&prevHadToken=0&landingPath=NotLandingPage&groups=C0001%3A1%2CC0002%3A0%2CC0003%3A0%2CC0004%3A0%2CV2STACK1%3A0%2CV2STACK42%3A0%2CBG397%3A1&iType=2&intType=2&crTime=1775781969818&geolocation=GB%3B&AwaitingReconsent=false; s_sq=%5B%5BB%5D%5D
pragma
no-cache
referer
https://www.espn.com/
sec-ch-ua
"Chromium";v="146", "Not-A.Brand";v="24", "Google Chrome";v="146"
sec-ch-ua-mobile
?0
sec-ch-ua-platform
"Windows"
sec-fetch-dest
script
sec-fetch-mode
no-cors
sec-fetch-site
same-site
user-agent
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36
""".strip()

headers = {}
for idx, line in enumerate(header_contents.splitlines()):
    if idx % 2 == 0:
        key = line.strip()
    else:
        value = line.strip()
        headers[key] = value

In [7]:
url = 'https://www.espn.com/nba/boxscore/_/gameId/401811025'
rsp = requests.get(url, headers=headers)
rsp.status_code

200

In [8]:
soup = BeautifulSoup(rsp.text, 'html.parser')

In [16]:
s = soup.find('script', string=lambda s: s and '__CONFIG__' in s)

In [18]:
import re
import json

text = s.string
config_match = re.search(r"window\['__CONFIG__'\]\s*=\s*(\{.*?\});", text)
espn_match = re.search(r"window\['__espnfitt__'\]\s*=\s*(\{.*?\});", text)

config = json.loads(config_match.group(1))
espn = json.loads(espn_match.group(1))

In [ ]:
# with open(f'/home/abraham/uni/ikt453/project/v1/data/espn___CONFIG__.json', 'w') as f:
#     json.dump(config, f, indent=4)

In [ ]:
from IPython.display import display, HTML

# display(HTML(rsp.text))